### ISSUE TITLE
feature requast not working

### ISSUE THREAD

**Issue by pro9code** [Dueris/Canvas#19]
### Spark link

n/a

### Expected behavior

be able to ask where a wiki for the api is

### Observed/Actual behavior

error

### Steps/models to reproduce

click on feature request

### Canvas version

n/a

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by Dreeam-qwq** [comment]
`I ticked all the boxes without actually reading them`

**Comment by pro9code** [comment]
Sorry. Where is the api wiki, though?

**Comment by Dueris** [comment]
ATM the current wiki is extremely out of date, but I can add it to the new website rewrite in a few hours

**Comment by pro9code** [comment]
Thanka
