### ISSUE TITLE
Rapid chunk loading crashes server.

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#27]
### Spark link

https://spark.lucko.me/pIdJVsxvui

### Stack trace

https://mclo.gs/shA0RAD

### Actions to reproduce (if known)

Load the server for the first time
Op yourself
Switch to spectator
Fly a random direction

### Canvas version

Current Purpur Version: 1.21-DEV-c8a38cd (MC: 1.21)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

### Other

Plugins:
- ViaVersion 5.0.1
- ViaBackwards 5.0.1

Client Version: 1.20.6

Standing still does not cause the issue even though the location correctly saves, so it does not seem to be related to any chunk in particular.
Update: Issue also does not seem happen when flying around in creative.
Update 2: Issue does arise when moving quickly using Riptide.
Update 3: Issue happened after I took 4 steps while messing with tick rate.

**Comment by TheDeafCreeper** [comment]
Ok further testing shows that the issue might be related to ViaVersion?
After removing ViaVersion and using a 1.21 client the issue seems to have stopped.

**Comment by Dueris** [comment]
This seems to be related to the other issue you were mentioning, after a new build is up with the fix I'll test this to see if it still occurs

**Comment by Dueris** [comment]
The issue has been marked resolved in another issue, this seems to be the same issue according to the stacktrace, so this is marked as resolved aswell: https://github.com/CraftCanvasMC/Canvas/issues/28
