### ISSUE TITLE
Server crash while loading chunks

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#30]
### Spark link

N/A

### Stack trace

https://mclo.gs/qQ6AwW6

### Actions to reproduce (if known)

Teleport into a full unloaded area.
See if it happens

### Canvas version

Current Purpur Version: 1.21-DEV-fdbdc43 (MC: 1.21)*
* You are running the latest version
Previous: 1.21-DEV-c8a38cd (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

### Other

Plugins: None
Client: 1.21

Crash does seem to be pretty rare, might have just got "lucky" to experience it second try.

**Comment by Dueris** [comment]
fixed
