### ISSUE TITLE
Most mobs don't wander while idle

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#31]
### Spark link

N/A

### Expected behavior

Mobs should wander around when they have nothing else to do.

### Observed/Actual behavior

Most mobs do not wander around.

### Steps/models to reproduce

Spawn a pig.
Watch the pig

### Canvas version

Current Purpur Version: 1.21-DEV-29f8121 (MC: 1.21)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

### Other

Plugins: None

The mobs in this list WILL move if they have a specific action in mind, such as following food or attacking a player, but will not wander when idle.
Mobs that DO NOT wander:
- Blaze
- Bogged
- Cat
- Cave Spider
- Chicken
- Cod
- Cow
- Creeper
- Dolphin
- Donkey
- Drowned
- Elder Guardian
- Enderman (Does not idle teleport either)
- Evoker
- Fox
- Endermite
- Guardian
- Horse
- Husk
- Iron Golem
- Llama
- Pig
- Panda
- Ocelot
- Mule
- Mooshroom
- Silverfish
- Salmon
- Ravager
- Sheep
- Pillager
- Polar Bear
- Pufferfish
- Skeleton
- Skeleton Horse
- Spider
- Stray
- Strider
- Snow Golem
- Trader Llama
- Tropical Fish
- Turtle
- Vindicator
- Witch
- Wither
- Wither Skeleton
- Wandering Trader (Villagers DO wander)
- Wolf
- Zombie Villager
- Zombie
- Zombified Pigland
- Zombie Horse

**Comment by Dueris** [comment]
closing this since this is mostly intended. I reduce the pathfinder rates of wandering when the entity is idle to reduce the amount of usage the pathfinder uses when it rly doesn't need to. iirc there is a config for it in canvas.yml, but I don't remember off the top of my head
