### ISSUE TITLE
[Minor] "Took too long to log in" error at high TPS

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#33]
### Spark link

N/A

### Expected behavior

You're able to log in succesfully

### Observed/Actual behavior

You get the error

### Steps/models to reproduce

Set TPS really high
Log out then back in

### Canvas version

Current Purpur Version: 1.21-DEV-29f8121 (MC: 1.21)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

### Other

Another thing probably not worth fixing (I believe this is also just a vanilla bug).

**Comment by Dueris** [comment]
this is vanilla, and canvas is running like 4x faster than it should, making the time(in ticks) until timeout is GREATLY reduced in seconds because the tps has 0 cap. marking as won't fix
