### ISSUE TITLE
Server crash with 250 "players" walking around

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#35]
### Spark link

Ping me if needed (I don't have a link)

### Stack trace

https://mclo.gs/tXnuY2i

### Actions to reproduce (if known)

It seems to be some sort of chunk loading thing, so load lots of chunks?

### Canvas version

Current Purpur Version: 1.21-DEV-0bfcfed (MC: 1.21)*
* You are running the latest version
Previous: 1.21-2259-b3709b1 (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by Dueris** [comment]
Easy fix, its with my chunk gen optimizations

**Comment by Dueris** [comment]
fixed
