### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#37]
### Spark link

N/A

### Stack trace

[crash-2024-07-12_17.39.09-server.txt](https://github.com/user-attachments/files/16197600/crash-2024-07-12_17.39.09-server.txt)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by Dueris** [comment]
fixed
