### ISSUE TITLE
please specify an api version for plugins requesting it.

### ISSUE THREAD

**Issue by pro9code** [Dueris/Canvas#4]
### Spark link

?

### Expected behavior

not api version unsupported on slimefun 4 and coreprotect

### Observed/Actual behavior

coreprotect dosn't work - please help!

### Steps/models to reproduce

install coreprotect

### Canvas version

latest-release
[20:21:55 WARN] [Minecraft]: Unable to match version to pattern! Report to Canvas!
[20:21:55 WARN] [Minecraft]: Pattern: ^([0-9\.]*)\-.*R
[20:21:55 WARN] [Minecraft]: Version: Unknown-Version

### Agreements

- [X] I am running the latest version of Canvas available from https://canvasmc-project.github.io/downloads/index.html.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by pro9code** [comment]
also this
[ex.pdf](https://github.com/CraftCanvasMC/Canvas/files/13482321/ex.pdf)

**Comment by pro9code** [comment]
and this
https://www.spigotmc.org/resources/1-9-1-20-fork-custom-recipes-and-crafting-craftenhance.111998/

**Comment by Dueris** [comment]
So slimefun and coreprotect don't work due to the Canvas api version breaking?

**Comment by Dueris** [comment]
Just double checking before I work on fixing this

**Comment by Dueris** [comment]
Damn I gotta update the issue template to the right download page lol

**Comment by pro9code** [comment]
Correct.

**Comment by Dueris** [comment]
K. Should be an easy fix, will work on it in abt 20 minutes

**Comment by Dueris** [comment]
(Ignore this message I'm testing to see if my webhook fix for the discord server worked)
Edit: it didn't lol

**Comment by Dueris** [comment]
Test again(final test before I just use --skip commits)

Edit: it worked

**Comment by Dueris** [comment]
Fixed. Merging with rebrand patch rn.

The issue was with me not changing the META-INF resource for getting the api version to the Canvas path. It's been resolved now and a build will be avalible shortly

**Comment by Dueris** [comment]
Pushing to downloads momentarily

**Comment by pro9code** [comment]
Thanks. This really helps a lot in testing plugins for my server.
