### ISSUE TITLE
Already sent chunk error

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#40]
### Spark link

N/A

### Stack trace

[crash-2024-07-12_19.07.10-server.txt](https://github.com/user-attachments/files/16198359/crash-2024-07-12_19.07.10-server.txt)

### Actions to reproduce (if known)

Have tnt load chunks

### Canvas version

Current Purpur Version: 1.21-DEV-6fb9cf2 (MC: 1.21)*
* You are running the latest version
Previous: 1.21-DEV-e7b957c (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by Dueris** [comment]
fixed? gonna wanna test this further
