### ISSUE TITLE
Crash on chunk load

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#41]
### Spark link

N/A

### Stack trace

[crash-2024-07-12_16.13.53-server.txt](https://github.com/user-attachments/files/16199310/crash-2024-07-12_16.13.53-server.txt)

### Actions to reproduce (if known)

Exact cause unknown

### Canvas version

Current Purpur Version: 1.21-DEV-6fb9cf2 (MC: 1.21)*
* You are running the latest version
Previous: 1.21-DEV-e7b957c (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by Dueris** [comment]
fixed
