### ISSUE TITLE
Crash reports say report to Purpur instead of report to Canvas

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#42]
### Spark link

N/A

### Expected behavior

The disclaimer at the top of the crash report should say:

DO NOT REPORT THIS TO PAPER/PURPUR! REPORT TO CANVAS INSTEAD!

### Observed/Actual behavior

The disclaimer actually says:

DO NOT REPORT THIS TO PAPER! REPORT TO PURPUR INSTEAD!

### Steps/models to reproduce

Crash the server (probably TNT time)

### Canvas version

Current Purpur Version: 1.21-DEV-6fb9cf2 (MC: 1.21)*
* You are running the latest version
Previous: 1.21-DEV-e7b957c (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by Dueris** [comment]
fixed
