### ISSUE TITLE
Some errors about the use of ModelEngine4

### ISSUE THREAD

**Issue by TH2403y** [Dueris/Canvas#50]
### Spark link

NONE

### Expected behavior

It was supposed to show the model.
![image](https://github.com/user-attachments/assets/ca23ddd0-6b86-4932-ab5e-4cb002b31a57)

### Observed/Actual behavior

https://paste.gg/p/anonymous/f313041fe64a442e98c5ea69388b1dd3. Only had some Error.

### Steps/models to reproduce

1.Use ModelEngine Plugin and Load one Model.
2.To summon Model Mob.

### Canvas version

[21:08:18 INFO]: Current Canvas Version: 1.21-DEV-712018f (MC: 1.21)*
* You are running the latest version
Previous: 1.21-130-b1b5d4c (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by TH2403y** [comment]
hi , are there any plans to fix MEG4 errors in the near future?

**Comment by Dueris** [comment]
fixed. build being pushed soon along with pufferfish upstream update
