### ISSUE TITLE
Crash after generating chunks as a spectator

### ISSUE THREAD

**Issue by CronixZero** [Dueris/Canvas#53]
### Spark link

https://spark.lucko.me/QBdSoULe7k

### Stack trace

https://haste.paul.wtf/ijizinavog

### Actions to reproduce (if known)

1. After creating a new server I decided to create a couple of worlds to test the performance of Canvas.
2. I entered the Nether through a Portal and swiftly exited it
3. Entered a newly generated world (Generated by catching a Spigot PortalEvent and recreating a world through the same WorldCreator with a different seed and name + rerouting the player to the newly generated)
4. Entered Spectator Mode, increased my speed with the mouse wheel and flew into one direction until the chunks didn't load anymore and the server crashed

### Canvas version

Current Canvas Version: 1.21.3-DEV-f641235 (MC: 1.21.3)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

### Other

More to point 3.)

In a Listener:
```java
World target = event.getTo().getWorld();

World createdWorld = worldService.createWorld(
        worldService
            .creator(target.getName())
            .copy(target)
            .seed(SEED_RANDOM.nextLong())
    );

    Location newLocation = event.getTo().clone();
    newLocation.setWorld(createdWorld);

    log.debug("Rerouted Player {} from World {} to {} because of {} Teleportation",
        event.getPlayer().getName(), from.getName(),
        createdWorld.getName(), event.getCause());
    event.setTo(newLocation);
```

`worldService#creator(String)` creates a World with a UUID + "_" + name
`worldService#createWorld(WorldCreator)` then uses the WorldCreator and creates a World with `Bukkit.createWorld`

**Comment by Dueris** [comment]
im now realizing i need to update the template to the new website link lmao.

is there a crash report? i can fix the errors in the logs you sent here tmrw. if there is a crash log send it and ill fix that too.

**Comment by CronixZero** [comment]
You're a hero.
I don't think that there's a Crash Report as I had to manually kill the process after it started generating 75mb of logs (Spammed with Thread Death Messages)

**Comment by Dueris** [comment]
alr np. ill get to work on this ASAP. might be late afternoon/early-evening PST when i can work on it.

**Comment by Dueris** [comment]
got the bug fixed a few days ago, been a bit busy irl so havent had time to push. gonna push the fix with an upstream and more optimizations :)

**Comment by Dueris** [comment]
fixed in rewrite
