### ISSUE TITLE
miltiverse/worldguard diasabling gui console

### ISSUE THREAD

**Issue by pro9code** [Dueris/Canvas#9]
### Spark link

[17:27:47 INFO] [spark]: The async-profiler engine is not supported for your os/arch (windows11/amd64), so the built-in Java engine will be used instead.

### Expected behavior

more console in gui

### Observed/Actual behavior

just cuts off

### Steps/models to reproduce

miltiverse
worldguard

### Canvas version

fb1e4ec

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by Dueris** [comment]
By any chance are the logs in the cmd prompt window being flooded with a warning? Bc that's a weird bug in the Canvas rewrite of the gui that I haven't figured out yet.

**Comment by Dueris** [comment]
That error causes that exact issue with the gui

**Comment by pro9code** [comment]
Every other launch seems to spawn a rogue thread, and I have to restart
the server

**Comment by Dueris** [comment]
The new thread is for log reading to try and keep it off the main thread

**Comment by pro9code** [comment]
will the 1.20.2 still be supported? important plugins such as coreprotect and worledit are not updated yet.

**Comment by Dueris** [comment]
I don't think so. The plugins you mentioned don't have an impact on the gui from my testing, meaning I can't replicate the issue. The only way to replicate it was with what I said before, with something breaking in the gui, which is a simple fix if i can figure out the issue. 1.20.2 builds will still be avalible tho on https://canvas.kesug.com/downloads

**Comment by pro9code** [comment]
Ok, thanks for the clarification.
